### ISSUE TITLE
PSArips not working

### ISSUE THREAD

**Issue by sherlockia2** [hyPnOtICDo0g/rss-chan#1]
https://x265.club/feed/ -- Unable to add this RSS link.
ERROR: `The link doesn't seem to be a RSS feed or it's not supported!`

**Comment by hyPnOtICDo0g** [comment]
I tested this URL locally & it works [fine](https://i.imgur.com/HoV6dh7.png). If you deployed the bot on Heroku or somewhere else,  pretty sure this domain is blocked. It's better to use a proxy of some sort if you wanna fetch feeds. Have a great day! :)
