### ISSUE TITLE
Actual <content> posting.

### ISSUE THREAD

**Issue by shifting-tides** [hyPnOtICDo0g/rss-chan#13]
Could you please add actual content posting? Take Twitter parsing by rss-bridge, for example. https://rss-bridge.ggc-project.de/?action=display&bridge=Twitter&context=By+username&u=elonmusk&norep=on&noretweet=on&nopinned=on&nopic=on&noimgscaling=on&format=Atom

As you can see, tweet text as well as attachments are stored in content, which is d.entries[0].content in feedparser. You can store images as links in Database instead of actually downloading them, and if you need to attach them - perform image downloading from links which are tied to post. This way, the database won't grow rapidly. rss-chan will turn into rss-mirrorchan! 

Perhaps you could just add the ability of choosing Atom elements per each subscription.

**Comment by hyPnOtICDo0g** [comment]
@shifting-tides 
> Could you please add actual content posting?

https://github.com/hyPnOtICDo0g/rss-chan/blob/7179de62377f2d3ce8258f47ef555b03c2200fc1/bot/modules/rsshandler.py#L206
I think you should just set `disable_web_page_preview` to `False` if you're not able to view media.

> Perhaps you could just add the ability of choosing Atom elements per each subscription.

You should probably check the template feature. Hit `/template` for help.

**Comment by shifting-tides** [comment]
It kind of works. item_description doesn't convert markdown to telegram's standard, which leaves markdown as it is. Web page preview also won't help in case I'm mirroring niche website. Telegram simply will not generate proper image preview for the website I'm mirroring, so the feature of extracting and attaching photos will be much appreciated.

**Comment by hyPnOtICDo0g** [comment]
Hmm, I get your point. But this is a generic bot, I cannot support specific feeds which have media and push them to telegram.

You could write a custom script which scrapes images from twitter at regular intervals and push them to telegram.

Will be closing this issue ticket.
