### ISSUE TITLE
[Feature Request] Add a custom message to feed entries

### ISSUE THREAD

**Issue by hyPnOtICDo0g** [hyPnOtICDo0g/rss-chan#4]
```
This is your new feed:
<item_name>
<item_url>
```
Here, `CUSTOM_MESSAGE` = "This is your new feed:".

**Comment by Ritikaa18** [comment]
> ```
> This is your new feed:
> <item_name>
> <item_url>
> ```
> 
> Here, `CUSTOM_MESSAGE` = "This is your new feed:".

Yes, <item_name> - Something like this for custom message too? So if I set different custom message for different feed, it'll print the according message for the feed. 
For ex, There's a Movie rss and tv rss from rarbg, I'll use /movie <item_url> for movie and /tv <item_url> like this.

> This is your new feed:
> <item_name>
> <item_url>

If you could add some more entries like <item_enclosureurl> and <item_magneturi> too, I can use that for available feeds. This would overall satisfy both my feature requests.

**Comment by hyPnOtICDo0g** [comment]
@Ritikaa18 As I said in the #2, this is a generic feedparser. Please tweak the code to your needs. The custom message will be set in your config & it will be global to all feeds. I still don't get the point of custom messages but since it'll be set as optional I really don't mind. This is how it's gonna [look](https://i.imgur.com/qaoU6Q0.png).

`CUSTOM_MESSAGE` is set as _New video in your feeds!_

If there are multiple feeds dumped to your chat at once, the custom message will be shown in all feeds.
