### ISSUE TITLE
deploy

### ISSUE THREAD

**Issue by manav1708** [hyPnOtICDo0g/rss-chan#7]
Heroku deploy button isn't working its giving 404 error please look into it

**Comment by hyPnOtICDo0g** [comment]
@manav1708 
Please include screenshots or logs when you open an issue.

**Comment by manav1708** [comment]
![Screenshot_2021-09-27-17-36-27-689_com brave browser](https://user-images.githubusercontent.com/67852790/134904956-c66f6bfa-8cfb-4ec5-b0ac-343b6981a09c.jpg)


Its stuck i wait around 30mins still nothing show up

I used deploy button from your repo's wiki

**Comment by hyPnOtICDo0g** [comment]
@manav1708 
Pretty sure something's wrong on your side. I just deployed it right now, & it works fine. 
I am not responsible for heroku's loading issues. Try switching your network at try once again.
