### ISSUE TITLE
[FEATURE REQUEST] greater comfort

### ISSUE THREAD

**Issue by yadianluffy** [hyPnOtICDo0g/rss-chan#9]
hello very incredible this rss bot works wonderfully but if you could add this improvement it would be even better and comfortable
currently looks like this

![Sin título](https://user-images.githubusercontent.com/88897873/147193691-20eaff51-9c9c-489b-953c-3cad1264adb1.png)

It would be better if it looks like this, do you think it would be possible to add that, thank you very much, I await your answer.

![Sin título1](https://user-images.githubusercontent.com/88897873/147193790-2e5c36df-ae7e-4f18-9f7e-c5ed1211a79c.png)

**Comment by hyPnOtICDo0g** [comment]
@yadianluffy 
This is a generic feed reader. The bot grabs the `<title>` & `<link>` fields only.  Not all websites support the fields you're asking me to include.

**Comment by yadianluffy** [comment]
I use it only for nyaa.si 
it would be nice if it said the size of the file

**Comment by hyPnOtICDo0g** [comment]
@yadianluffy 
No. I cannot add support to particular site requests.
